### PR TITLE
Add wrappers for new universal analytics features.

### PR DESCRIPTION
**Pull request by rdwallis**

### CODE REVIEW

**Comment by rdwallis** [comment]
There are two minor api changes here to do with spelling:

In AnalyticsOptions:
```
public ApptrackingOptions apptrackingOptions
becomes
public AppTrackingOptions appTrackingOptions

and similar for TrafficsourceOptions.

---

These were originally generated by parsing the analytics javadoc which is why they're not capitalized correctly.

Obviously fixing the capitalization breaks things but if we don't fix it now it'll be broken forever.

But I'll tank the changes if others think it's not worth the api breakage.

**Comment by christiangoudreau** [comment]
LGTM

**Comment by meriouma** [comment]
LGTM

**Comment by meriouma** [comment]
LGTM

**Pull request merged**
