### PR TITLE
Allow disabling injection of analytics.js

### PR DESCRIPTION
**Pull request by meriouma**

### CODE REVIEW

**Comment by rdwallis** [comment]
lgtm but why do you want to stop analytics.js being injected?

**Comment by meriouma** [comment]
We want/need to put it in the static html file

**Comment by Chris-V** [comment]
lgtm

**Comment by rdwallis** [comment]
Ok I thought analytics.js wouldn't load if it was already injected but
looking at the code it does look like the script is injected again.


I don't think running analytics.js twice will have side effects.  But no
harm in preventing it.

**Pull request merged**
